import dotenv from "dotenv";
import Product from "../models/Product";
import Category from "../models/Category";
import Testimonial from "../models/Testimonial";
import connectDB from "../config/database";

dotenv.config();

/**
 * Seed Categories Data
 */
const seedCategories = async () => {
  const categories = [
    { name: "Smartphones", nameBn: "স্মার্টফোন", slug: "smartphones", icon: "smartphone" },
    { name: "Laptops", nameBn: "ল্যাপটপ", slug: "laptops", icon: "laptop" },
    { name: "Fashion", nameBn: "ফ্যাশন", slug: "fashion", icon: "shirt" },
    { name: "Watches", nameBn: "ঘড়ি", slug: "watches", icon: "watch" },
    { name: "Beauty", nameBn: "বিউটি", slug: "beauty", icon: "heart" },
    { name: "Home", nameBn: "হোম", slug: "home", icon: "home" },
    { name: "Camera", nameBn: "ক্যামেরা", slug: "camera", icon: "camera" },
    { name: "Gaming", nameBn: "গেমিং", slug: "gaming", icon: "gamepad" },
    { name: "Audio", nameBn: "অডিও", slug: "audio", icon: "headphones" },
    { name: "Accessories", nameBn: "অ্যাকসেসরিজ", slug: "accessories", icon: "shopping-bag" },
    { name: "Baby", nameBn: "বেবি", slug: "baby", icon: "baby" },
    { name: "Sports", nameBn: "স্পোর্টস", slug: "sports", icon: "dumbbell" },
  ];

  // Clear existing categories
  await Category.deleteMany({});
  console.log("🗑️  Cleared existing categories");

  // Insert categories
  await Category.insertMany(categories);
  console.log(`✅ Seeded ${categories.length} categories`);
};

/**
 * Seed Products Data
 */
const seedProducts = async () => {
  const products = [
    // Electronics
    {
      name: "Samsung Galaxy S24 Ultra",
      nameBn: "স্যামসাং গ্যালাক্সি এস২৪ আল্ট্রা",
      description: "Latest flagship smartphone with advanced camera and AI features",
      descriptionBn: "সর্বাধুনিক ফ্ল্যাগশিপ স্মার্টফোন উন্নত ক্যামেরা এবং AI ফিচার সহ",
      price: 125000,
      originalPrice: 150000,
      discount: 17,
      image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500",
      images: [
        "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500",
      ],
      category: "smartphones",
      categoryBn: "স্মার্টফোন",
      inStock: true,
      stock: 50,
      rating: 4.8,
      reviews: 234,
      isFeatured: true,
      isFlashSale: true,
      isTrending: true,
      tags: ["smartphone", "samsung", "flagship"],
    },
    {
      name: "iPhone 15 Pro Max",
      nameBn: "আইফোন ১৫ প্রো ম্যাক্স",
      description: "Apple's latest premium smartphone with titanium design",
      descriptionBn: "অ্যাপলের সর্বাধুনিক প্রিমিয়াম স্মার্টফোন টাইটানিয়াম ডিজাইন সহ",
      price: 145000,
      originalPrice: 160000,
      discount: 9,
      image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500",
      category: "smartphones",
      categoryBn: "স্মার্টফোন",
      inStock: true,
      stock: 30,
      rating: 4.9,
      reviews: 189,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["smartphone", "apple", "iphone"],
    },
    {
      name: "MacBook Pro 16-inch",
      nameBn: "ম্যাকবুক প্রো ১৬-ইঞ্চি",
      description: "Powerful laptop for professionals with M3 chip",
      descriptionBn: "M3 চিপ সহ পেশাদারদের জন্য শক্তিশালী ল্যাপটপ",
      price: 280000,
      originalPrice: 320000,
      discount: 13,
      image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500",
      category: "laptops",
      categoryBn: "ল্যাপটপ",
      inStock: true,
      stock: 15,
      rating: 4.7,
      reviews: 95,
      isFeatured: true,
      isFlashSale: true,
      isTrending: false,
      tags: ["laptop", "apple", "macbook"],
    },
    {
      name: "Sony WH-1000XM5 Headphones",
      nameBn: "সনি WH-1000XM5 হেডফোন",
      description: "Premium noise-cancelling wireless headphones",
      descriptionBn: "প্রিমিয়াম নয়েজ-ক্যানসেলিং ওয়্যারলেস হেডফোন",
      price: 35000,
      originalPrice: 40000,
      discount: 13,
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
      category: "audio",
      categoryBn: "অডিও",
      inStock: true,
      stock: 40,
      rating: 4.6,
      reviews: 156,
      isFeatured: false,
      isFlashSale: true,
      isTrending: true,
      tags: ["headphones", "audio", "wireless"],
    },
    // Fashion
    {
      name: "Men's Cotton T-Shirt",
      nameBn: "পুরুষদের সুতি টি-শার্ট",
      description: "Comfortable cotton t-shirt for everyday wear",
      descriptionBn: "দৈনন্দিন পরার জন্য আরামদায়ক সুতি টি-শার্ট",
      price: 899,
      originalPrice: 1299,
      discount: 31,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
      category: "fashion",
      categoryBn: "ফ্যাশন",
      inStock: true,
      stock: 100,
      rating: 4.3,
      reviews: 78,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["tshirt", "men", "cotton"],
    },
    {
      name: "Women's Designer Saree",
      nameBn: "মহিলাদের ডিজাইনার শাড়ি",
      description: "Elegant designer saree for special occasions",
      descriptionBn: "বিশেষ অনুষ্ঠানের জন্য মার্জিত ডিজাইনার শাড়ি",
      price: 4500,
      originalPrice: 6500,
      discount: 31,
      image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500",
      category: "fashion",
      categoryBn: "ফ্যাশন",
      inStock: true,
      stock: 25,
      rating: 4.5,
      reviews: 42,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["saree", "women", "traditional"],
    },
    {
      name: "Leather Jacket",
      nameBn: "লেদার জ্যাকেট",
      description: "Genuine leather jacket for men and women",
      descriptionBn: "পুরুষ ও মহিলাদের জন্য আসল লেদার জ্যাকেট",
      price: 8500,
      originalPrice: 12000,
      discount: 29,
      image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
      category: "fashion",
      categoryBn: "ফ্যাশন",
      inStock: true,
      stock: 20,
      rating: 4.4,
      reviews: 67,
      isFeatured: false,
      isFlashSale: true,
      isTrending: true,
      tags: ["jacket", "leather", "unisex"],
    },
    {
      name: "Running Shoes",
      nameBn: "রানিং শু",
      description: "Comfortable running shoes for sports and fitness",
      descriptionBn: "খেলাধুলা এবং ফিটনেসের জন্য আরামদায়ক রানিং শু",
      price: 3200,
      originalPrice: 4500,
      discount: 29,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
      category: "fashion",
      categoryBn: "ফ্যাশন",
      inStock: true,
      stock: 60,
      rating: 4.2,
      reviews: 123,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["shoes", "sports", "running"],
    },
    // Beauty
    {
      name: "Lakme Face Cream",
      nameBn: "লাকমে ফেস ক্রিম",
      description: "Moisturizing face cream for all skin types",
      descriptionBn: "সব ধরনের ত্বকের জন্য ময়েশ্চারাইজিং ফেস ক্রিম",
      price: 450,
      originalPrice: 600,
      discount: 25,
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500",
      category: "beauty",
      categoryBn: "বিউটি",
      inStock: true,
      stock: 200,
      rating: 4.1,
      reviews: 89,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["skincare", "cream", "lakme"],
    },
    {
      name: "Maybelline Lipstick Set",
      nameBn: "মেবেলিন লিপস্টিক সেট",
      description: "Set of 5 premium lipstick shades",
      descriptionBn: "৫টি প্রিমিয়াম লিপস্টিক শেডের সেট",
      price: 1200,
      originalPrice: 1800,
      discount: 33,
      image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
      category: "beauty",
      categoryBn: "বিউটি",
      inStock: true,
      stock: 80,
      rating: 4.6,
      reviews: 145,
      isFeatured: true,
      isFlashSale: true,
      isTrending: true,
      tags: ["makeup", "lipstick", "maybelline"],
    },
    {
      name: "Garnier Hair Mask",
      nameBn: "গার্নিয়ার হেয়ার মাস্ক",
      description: "Deep conditioning hair mask for damaged hair",
      descriptionBn: "ক্ষতিগ্রস্ত চুলের জন্য গভীর কন্ডিশনিং হেয়ার মাস্ক",
      price: 550,
      originalPrice: 750,
      discount: 27,
      image: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=500",
      category: "beauty",
      categoryBn: "বিউটি",
      inStock: true,
      stock: 150,
      rating: 4.3,
      reviews: 112,
      isFeatured: false,
      isFlashSale: false,
      isTrending: true,
      tags: ["haircare", "mask", "garnier"],
    },
    {
      name: "Nivea Sunscreen SPF 50",
      nameBn: "নিভিয়া সানস্ক্রিন SPF 50",
      description: "High protection sunscreen for face and body",
      descriptionBn: "মুখ এবং শরীরের জন্য উচ্চ সুরক্ষা সানস্ক্রিন",
      price: 650,
      originalPrice: 850,
      discount: 24,
      image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500",
      category: "beauty",
      categoryBn: "বিউটি",
      inStock: true,
      stock: 120,
      rating: 4.4,
      reviews: 98,
      isFeatured: true,
      isFlashSale: true,
      isTrending: false,
      tags: ["skincare", "sunscreen", "nivea"],
    },
    // More products for variety
    {
      name: "Canon EOS R6 Camera",
      nameBn: "ক্যানন EOS R6 ক্যামেরা",
      description: "Professional mirrorless camera with 4K video",
      descriptionBn: "4K ভিডিও সহ পেশাদার মিররলেস ক্যামেরা",
      price: 220000,
      originalPrice: 250000,
      discount: 12,
      image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500",
      category: "camera",
      categoryBn: "ক্যামেরা",
      inStock: true,
      stock: 10,
      rating: 4.8,
      reviews: 56,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["camera", "canon", "photography"],
    },
    {
      name: "PlayStation 5",
      nameBn: "প্লেস্টেশন ৫",
      description: "Latest gaming console with 4K gaming",
      descriptionBn: "4K গেমিং সহ সর্বাধুনিক গেমিং কনসোল",
      price: 65000,
      originalPrice: 75000,
      discount: 13,
      image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=500",
      category: "gaming",
      categoryBn: "গেমিং",
      inStock: true,
      stock: 8,
      rating: 4.9,
      reviews: 234,
      isFeatured: true,
      isFlashSale: true,
      isTrending: true,
      tags: ["gaming", "console", "playstation"],
    },
    // Watches
    {
      name: "Rolex Submariner",
      nameBn: "রোলেক্স সাবমেরিনার",
      description: "Iconic luxury dive watch with automatic movement",
      descriptionBn: "অটোম্যাটিক মুভমেন্ট সহ আইকনিক লাক্সারি ডাইভ ওয়াচ",
      price: 1500000,
      originalPrice: 1800000,
      discount: 17,
      image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500",
      category: "watches",
      categoryBn: "ঘড়ি",
      inStock: true,
      stock: 3,
      rating: 4.9,
      reviews: 45,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["watch", "luxury", "rolex", "diving"],
    },
    {
      name: "Seiko Automatic Watch",
      nameBn: "সেইকো অটোম্যাটিক ওয়াচ",
      description: "Reliable automatic watch for daily wear",
      descriptionBn: "দৈনন্দিন পরার জন্য নির্ভরযোগ্য অটোম্যাটিক ওয়াচ",
      price: 25000,
      originalPrice: 35000,
      discount: 29,
      image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500",
      category: "watches",
      categoryBn: "ঘড়ি",
      inStock: true,
      stock: 25,
      rating: 4.4,
      reviews: 89,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["watch", "automatic", "seiko"],
    },
    // Home products
    {
      name: "Smart LED TV 55-inch",
      nameBn: "স্মার্ট LED টিভি ৫৫-ইঞ্চি",
      description: "4K Ultra HD Smart TV with built-in streaming apps",
      descriptionBn: "বিল্ট-ইন স্ট্রিমিং অ্যাপস সহ 4K আল্ট্রা HD স্মার্ট টিভি",
      price: 85000,
      originalPrice: 100000,
      discount: 15,
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500",
      category: "home",
      categoryBn: "হোম",
      inStock: true,
      stock: 12,
      rating: 4.6,
      reviews: 127,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["tv", "smart", "4k", "home"],
    },
    {
      name: "Air Conditioner 1.5 Ton",
      nameBn: "এয়ার কন্ডিশনার ১.৫ টন",
      description: "Energy-efficient split AC with inverter technology",
      descriptionBn: "ইনভার্টার টেকনোলজি সহ এনার্জি-এফিশিয়েন্ট স্প্লিট AC",
      price: 65000,
      originalPrice: 75000,
      discount: 13,
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500",
      category: "home",
      categoryBn: "হোম",
      inStock: true,
      stock: 8,
      rating: 4.5,
      reviews: 76,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["ac", "cooling", "home", "appliance"],
    },
    // Accessories
    {
      name: "Wireless Charging Pad",
      nameBn: "ওয়্যারলেস চার্জিং প্যাড",
      description: "Fast wireless charging pad compatible with all devices",
      descriptionBn: "সব ডিভাইসের সাথে কম্প্যাটিবল ফাস্ট ওয়্যারলেস চার্জিং প্যাড",
      price: 1500,
      originalPrice: 2000,
      discount: 25,
      image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500",
      category: "accessories",
      categoryBn: "অ্যাকসেসরিজ",
      inStock: true,
      stock: 50,
      rating: 4.3,
      reviews: 98,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["charger", "wireless", "accessory"],
    },
    {
      name: "Bluetooth Speaker",
      nameBn: "ব্লুটুথ স্পিকার",
      description: "Portable Bluetooth speaker with excellent sound quality",
      descriptionBn: "চমৎকার সাউন্ড কোয়ালিটি সহ পোর্টেবল ব্লুটুথ স্পিকার",
      price: 3500,
      originalPrice: 5000,
      discount: 30,
      image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
      category: "accessories",
      categoryBn: "অ্যাকসেসরিজ",
      inStock: true,
      stock: 35,
      rating: 4.4,
      reviews: 145,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["speaker", "bluetooth", "audio", "portable"],
    },
    // Baby products
    {
      name: "Baby Stroller",
      nameBn: "বেবি স্ট্রলার",
      description: "Lightweight and foldable baby stroller with safety features",
      descriptionBn: "সেফটি ফিচার সহ লাইটওয়েট এবং ফোল্ডেবল বেবি স্ট্রলার",
      price: 18500,
      originalPrice: 22000,
      discount: 16,
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500",
      category: "baby",
      categoryBn: "বেবি",
      inStock: true,
      stock: 15,
      rating: 4.5,
      reviews: 67,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["stroller", "baby", "kids"],
    },
    {
      name: "Baby Diapers Pack",
      nameBn: "বেবি ডায়াপার প্যাক",
      description: "Premium quality baby diapers with extra absorbency",
      descriptionBn: "এক্সট্রা অ্যাবসরবেন্সি সহ প্রিমিয়াম কোয়ালিটি বেবি ডায়াপার",
      price: 1200,
      originalPrice: 1500,
      discount: 20,
      image: "https://images.unsplash.com/photo-1544569226-44165ff6e324?w=500",
      category: "baby",
      categoryBn: "বেবি",
      inStock: true,
      stock: 100,
      rating: 4.6,
      reviews: 203,
      isFeatured: true,
      isFlashSale: false,
      isTrending: true,
      tags: ["diapers", "baby", "essentials"],
    },
    // Sports products
    {
      name: "Yoga Mat",
      nameBn: "ইয়োগা ম্যাট",
      description: "Non-slip yoga mat for comfortable workouts",
      descriptionBn: "আরামদায়ক ওয়ার্কআউটের জন্য নন-স্লিপ ইয়োগা ম্যাট",
      price: 2200,
      originalPrice: 3000,
      discount: 27,
      image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500",
      category: "sports",
      categoryBn: "স্পোর্টস",
      inStock: true,
      stock: 40,
      rating: 4.3,
      reviews: 89,
      isFeatured: false,
      isFlashSale: true,
      isTrending: false,
      tags: ["yoga", "fitness", "mat", "exercise"],
    },
    {
      name: "Dumbbell Set 20kg",
      nameBn: "ডাম্বেল সেট ২০কে.জি.",
      description: "Adjustable dumbbell set for home workouts",
      descriptionBn: "হোম ওয়ার্কআউটের জন্য অ্যাডজাস্টেবল ডাম্বেল সেট",
      price: 8500,
      originalPrice: 12000,
      discount: 29,
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500",
      category: "sports",
      categoryBn: "স্পোর্টস",
      inStock: true,
      stock: 20,
      rating: 4.7,
      reviews: 156,
      isFeatured: true,
      isFlashSale: true,
      isTrending: true,
      tags: ["dumbbell", "weights", "fitness", "gym"],
    },
  ];

  // Clear existing products
  await Product.deleteMany({});
  console.log("🗑️  Cleared existing products");

  // Insert products
  await Product.insertMany(products);
  console.log(`✅ Seeded ${products.length} products`);
};

/**
 * Seed Testimonials Data
 */
const seedTestimonials = async () => {
  const testimonials = [
    {
      name: "Rahman Ahmed",
      nameBn: "রহমান আহমেদ",
      rating: 5,
      comment: "Excellent service and fast delivery! Very satisfied with my purchase.",
      commentBn: "চমৎকার সেবা এবং দ্রুত ডেলিভারি! আমার কেনাকাটা নিয়ে খুবই সন্তুষ্ট।",
      location: "Dhaka",
      verified: true,
    },
    {
      name: "Fatima Khan",
      nameBn: "ফাতিমা খান",
      rating: 5,
      comment: "Best online shopping experience in Bangladesh. Highly recommended!",
      commentBn: "বাংলাদেশে সেরা অনলাইন শপিং অভিজ্ঞতা। অত্যন্ত সুপারিশকৃত!",
      location: "Chittagong",
      verified: true,
    },
    {
      name: "Karim Uddin",
      nameBn: "করিম উদ্দিন",
      rating: 4,
      comment: "Good quality products at reasonable prices. Will shop again.",
      commentBn: "যুক্তিসঙ্গত দামে ভালো মানের প্রোডাক্ট। আবার কেনাকাটা করব।",
      location: "Sylhet",
      verified: true,
    },
    {
      name: "Ayesha Begum",
      nameBn: "আয়েশা বেগম",
      rating: 5,
      comment: "Love the fashion collection! Fast shipping and great customer service.",
      commentBn: "ফ্যাশন কালেকশনটি খুবই ভালো লাগে! দ্রুত শিপিং এবং চমৎকার গ্রাহক সেবা।",
      location: "Rajshahi",
      verified: true,
    },
    {
      name: "Hasan Ali",
      nameBn: "হাসান আলী",
      rating: 4,
      comment: "Great deals on electronics. COD option is very convenient.",
      commentBn: "ইলেকট্রনিক্সে চমৎকার ডিল। COD অপশনটি খুবই সুবিধাজনক।",
      location: "Khulna",
      verified: true,
    },
    {
      name: "Nusrat Jahan",
      nameBn: "নুসরাত জাহান",
      rating: 5,
      comment: "Amazing beauty products collection. Authentic products and fast delivery!",
      commentBn: "চমৎকার বিউটি প্রোডাক্ট কালেকশন। আসল প্রোডাক্ট এবং দ্রুত ডেলিভারি!",
      location: "Dhaka",
      verified: true,
    },
  ];

  // Clear existing testimonials
  await Testimonial.deleteMany({});
  console.log("🗑️  Cleared existing testimonials");

  // Insert testimonials
  await Testimonial.insertMany(testimonials);
  console.log(`✅ Seeded ${testimonials.length} testimonials`);
};

/**
 * Main seed function
 */
const seedDatabase = async () => {
  try {
    // Connect to database
    await connectDB();

    // Seed data
    await seedCategories();
    await seedProducts();
    await seedTestimonials();

    console.log("🎉 Database seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
};

// Run seed function
seedDatabase();
